/*
 * File: app/view/ProjectView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ScrumApp.view.ProjectView', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.projectview',

    config: {
        id: 'projectView',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Web Project',
                items: [
                    {
                        xtype: 'button',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                title: 'Backlog',
                iconCls: 'organize',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                ui: 'action',
                                iconAlign: 'bottom',
                                iconMask: true,
                                text: 'Add'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        iconCls: '',
                        title: 'Open',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    },
                    {
                        xtype: 'list',
                        iconCls: '',
                        title: 'In Progress',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    },
                    {
                        xtype: 'list',
                        title: 'Completed',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                title: 'Tasks',
                activeItem: 1,
                iconCls: 'compose',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                ui: 'action',
                                iconAlign: 'bottom',
                                iconMask: true,
                                text: 'Add'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        iconCls: '',
                        title: 'Open',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    },
                    {
                        xtype: 'list',
                        iconCls: '',
                        title: 'In Progress',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    },
                    {
                        xtype: 'list',
                        title: 'Completed',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});