/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
  enabled: true
});

Ext.application({
  models: [
  'Project',
  'Task'
  ],
  views: [
    'MainPanel',
    'ProjectView',
    'MyTasksPanel',
    'TaskForm',
    'BacklogForm',
    'MyFormPanel3'
  ],
  stores: [
    'TaskStore',
    'ProjectStore'  
  ],
  name: 'ScrumApp',
  controllers: [
    'MegaMind'
  ],

  launch: function() {
    Ext.onReady(function(){
      s = Ext.getStore('taskSyncStore');
      s.setSyncRemovedRecords(true); // TODO hacky
      s.loadLocal(function(){
        if(s.getCount() == 0){
          s.loadServer();
        }
      });

      projectStore = Ext.getStore('projectSyncStore');
      projectStore.setSyncRemovedRecords(true); // TODO hacky
      projectStore.loadLocal(function(){
        if(projectStore.getCount()== 0){
          projectStore.loadServer();
        }
      });
    });

    ScrumApp.app.getHistory().on('change', function() {
        if (!String(window.location.hash).substr(1)) {
            Ext.Viewport.setActiveItem(0);
        };
    }, this);

    Ext.create('ScrumApp.view.MainPanel', { fullscreen: true });
  }

});
