/*
 * File: app/controller/MegaMind.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ScrumApp.controller.MegaMind', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'projects/:id': 'showProject',
            'tasks/:id': 'editTask'
        },

        refs: {
            projectView: '#projectView',
            taskForm: '#TaskForm'
        }
    },

    showProject: function(id) {
        view= this.getProjectView();

        if (view == undefined) {
            view = Ext.Viewport.add({
                xtype: "projectview"
            });
        }

        Ext.Viewport.setActiveItem(view);
    },

    editTask: function(id) {
        view = this.getTaskForm();

        if(view == undefined){
            view = Ext.Viewport.add({
                xtype: 'taskform'
            });
        }
        task = Ext.getStore('taskSyncStore').getById(id);
        if(task != undefined){
            view.setRecord(task);
            Ext.Viewport.setActiveItem(view);
        }else{
            Ext.Msg.alert('Could not load Task ' + id);
        }

    },
    updateTaskRecord: function(record, vals) {
        s = Ext.getStore('taskSyncStore');
        record.set('name', vals.name);
        Ext.blub= record;
        console.dir(record.get('name'));
        //record.set('comment', vals.comment);
        s.sync();
        history.back();
    }

});
