/*
 * File: app/controller/MegaMind.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ScrumApp.controller.MegaMind', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'projects/new': 'newProject',
            'projects/:id': 'showProject',
            'projects/:id/edit': 'editProject',
            'tasks/:id': 'editTask'
        },

        refs: {
            newProjectForm: '#newProjectForm',
            projectView: '#projectView',
            editProjectForm: '#editProjectForm',
            taskForm: '#TaskForm'
        }
    },

    newProject: function() {
        view= this.getNewProjectForm();

        if (view == undefined) {
            view = Ext.Viewport.add({
                xtype: 'newprojectform'
            });
        }

        Ext.Viewport.setActiveItem(view);
    },

    createProject: function(vals) {
        s = Ext.getStore('projectSyncStore');
        s.add({name: vals.name, description: vals.description});
        s.sync();
        history.back();
    },

    showProject: function(id) {
        view= this.getProjectView();

        if (view == undefined) {
            view = Ext.Viewport.add({
                xtype: "projectview"
            });
        }

        Ext.Viewport.setActiveItem(view);
    },

    editProject: function(id){

        view = this.getEditProjectForm();

        if(view == undefined){
            view = Ext.Viewport.add({
                xtype: 'editprojectform'
            });
        }
        project = Ext.getStore('projectSyncStore').getById(id);
        if(project != undefined){
            view.setRecord(project);
            Ext.Viewport.setActiveItem(view);
        }else{
            Ext.Msg.alert('Could not load Project ' + id);
        }

    },

    updateProjectRecord: function(record, vals) {
        s = Ext.getStore('projectSyncStore');
        record.set('name', vals.name);
        record.set('description', vals.description);
        s.sync();
        history.back();
    },

    editTask: function(id) {
        view = this.getTaskForm();

        if(view == undefined){
            view = Ext.Viewport.add({
                xtype: 'taskform'
            });
        }
        task = Ext.getStore('taskSyncStore').getById(id);
        if(task != undefined){
            view.setRecord(task);
            Ext.Viewport.setActiveItem(view);
        }else{
            Ext.Msg.alert('Could not load Task ' + id);
        }

    },
    updateTaskRecord: function(record, vals) {
        s = Ext.getStore('taskSyncStore');
        record.set('name', vals.name);
        record.set('description', vals.description);
        record.set('estimated_time', vals.estimated_time);
        record.set('state', vals.state);
        //record.set('comment', vals.comment);
        s.sync();
        history.back();
    }

});
